version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: unlock_service_db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: unlock_service